# Generated by Django 4.2.6 on 2023-10-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=155, verbose_name='Фамилия')),
                ('lastname', models.CharField(max_length=155, verbose_name='Имя')),
                ('age', models.PositiveIntegerField(verbose_name='Возраст')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
    ]
